# Generated by Django 3.0.4 on 2020-03-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('Author_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=1000)),
                ('Discription', models.CharField(default=' ', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=1000)),
                ('Discription', models.CharField(default=' ', max_length=5000)),
            ],
        ),
    ]
